### PR TITLE
docs(sbb-stepper): improve stories

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**

### CODE REVIEW

**Review by kyubisation — APPROVED** [review]
LGTM 👍 
Thanks! 😃

**Review by jeripeierSBB — APPROVED** [review]
LGTM thank you :)

**Review by dauriamarco — CHANGES_REQUESTED** [review]
Thank you! A comment on the step content and the length of the labels: they need to be different lengths to correctly test all step change animations, in the horizontal variants the content should be of a different number of lines to see the change in height and the same for long labels in the vertical variant to correctly test the marker line animation.

**Review by dauriamarco — APPROVED** [review]
LGTM 👍

**Pull request merged**
