### PR TITLE
fix: integrity

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**
`yarn format` on lit-migration branch

### CODE REVIEW

**Review by TomMenga — APPROVED** [review]
Outstanding work

**Review by dauriamarco — APPROVED** [review]
LGTM 👍

**Review by jeripeierSBB — APPROVED** [review]
Still wonder why it has passed once. :/

**Comment by jeripeierSBB** [comment]
I guess we need to fix the yarn integrity command in "package.json"

**Review by jeripeierSBB — CHANGES_REQUESTED** [review]
May you fix the yarn command in package.json so it will be active again during builds?

**Comment by DavideMininni-Fincons** [comment]
> May you fix the yarn command in package.json so it will be active again during builds?

Sure, i'll try

**Review by jeripeierSBB — APPROVED** [review]
Yeah!

**Comment by DavideMininni-Fincons** [comment]
@jeripeierSBB should I add the build in the integrity script?
so changing to `'integrity': 'npm-run-all --sequential build:components format'`?

**Pull request merged**
