### PR TITLE
fix(sbb-button): fix gap between icon and text for size s

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**

### CODE REVIEW

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks!

**Comment by jeripeierSBB** [comment]
@DavideMininni-Fincons could you maybe check, why our new visual regression tests dis not find this visual change. Are we missing something?

**Comment by DavideMininni-Fincons** [comment]
> @DavideMininni-Fincons could you maybe check, why our new visual regression tests dis not find this visual change. Are we missing something?

I'm not totally aware of how it should exactly works, but if i download the artifact from 'Store visual regression output'  https://github.com/sbb-design-systems/lyne-components/actions/runs/9176517207/job/25232514058?pr=2678 i see it's empty
the UI tests looks fine

**Comment by jeripeierSBB** [comment]
@DavideMininni-Fincons I think the change you made should generate a diff (like it is in Chromatic), but it did not generate one. Can you check if size s is really tested? Check button.snapshot.spec.ts

**Comment by DavideMininni-Fincons** [comment]
> @DavideMininni-Fincons I think the change you made should generate a diff (like it is in Chromatic), but it did not generate one. Can you check if size s is really tested? Check button.snapshot.spec.ts

solved as suggested, diffs are visible in https://lyne-components-visual-regression-diff-pr2678.app.sbb.ch/

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks

**Comment by mcilurzo** [comment]
LGTM, thanks

**Review by TomMenga — APPROVED** [review]
LGTM 👍

**Pull request merged**
