### PR TITLE
test(sbb-selection-expansion-panel): add visual spec

### PR DESCRIPTION
**Pull request by TomMenga**

### CODE REVIEW

**Review by MarioCastigliano — APPROVED** [review]
Looking good, maybe I would try to optimize the number of screenshots since for all the cases where the panel is closed the visual tests on the radio-button/checkbox would practically overlap

**Review by DavideMininni-Fincons — APPROVED** [review]
Looks good!

**Review by jeripeierSBB — COMMENTED** [review]
Basically looks good. One thought:
Comparing https://lyne-components-visual-regression-diff-pr2895.app.sbb.ch/compare/sbb-selection-expansion-panel/checkbox_group_with_error to https://lyne-components-visual-regression-diff-pr2895.app.sbb.ch/compare/sbb-selection-expansion-panel/radio_button_group_with_error has a shift between the price. is this only an example problem or do we have style problems in the component itself?

**Comment by TomMenga** [comment]
> https://lyne-components-visual-regression-diff-pr2895.app.sbb.ch/compare/sbb-selection-expansion-panel/checkbox_group_with_error

I was already investigating it and I'd say it's a component problem. This is due to the different "dom structure" between the radio and the checkbox. 
Since the fix might impact several components, I'd like a baseline to compare to. So I'm going to merge this and open a new one for the fix

**Pull request merged**
