### PR TITLE
feat: keep action elements focusable when disabled

### LINKED ISSUE #2862: [Bug]: focus on disabled buttons
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.2.0

### Operating system

Windows 10

### Browser / Browser version

Chrome  126.0.6478.127

### Input mode

Mouse/Keyboard

### Additional settings

_No response_

### What happened?

At this moment disabled Buttons are not focusable for blind users. You can overwrite this with the tabIndex but this is not working in the DialogActions.
They should be focusable aswell, so that blind users can get information about the status. 
I think there should be  a prop to make this possible.

### Steps to reproduce the issue

1. disabled button on view
2. try to tab to a button
you cant tab to the disabled button

### Relevant log output

_No response_

--------------------------

## Implementation Details

- Remove tabindex logic for disabled buttons (all types of buttons, but not form elements)
- Add accessibility documentation for button components to recommend adding aria references to describe why the button is disabled (from consumer side)

### PR DESCRIPTION
**Pull request by TomMenga**
## Notes to reviewer

I believe that not all the button-like components that previously extended the `SbbDisabledTabIndexActionMixin` should be part of this development. 
The components that, imho, should be excluded are:
- `sbb-popover-trigger`
- `sbb-slider`

Not sure about:
- `sbb-mini-button` => In some cases it should be focusable (mini-button-group) and in others it should not (e.g. when it's part of a form field)
- link and button-links

## TODO
- Decide what to do with arrow navigation (especially for the sbb-menu)

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/sbb-design-systems/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #2862 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../docs/REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- For a11y purposes, keep button-like elements focusable when disabled

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [x] Safari Desktop
- [x] Chrome Mobile
- [x] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [x] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [x] NVDA Chrome Desktop
- [x] VoiceOver Safari Desktop
- [x] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by TomMenga** [comment]
> A topic that came to my mind was that we have several components where we implemented arrow key navigation. Normally (as I remember) we exclude the disabled ones (e.g. menu.ts line 153). Maybe this still makes sense, but it would not be the same as arriving with `tab` there. Especially for the menu where both navigations are possible. But there are other components I think.

I believe the menu is the only component allowing both arrow and tab navigation. In general, if there is arrow navigation, you cannot tab between them

**Comment by jeripeierSBB** [comment]
> > A topic that came to my mind was that we have several components where we implemented arrow key navigation. Normally (as I remember) we exclude the disabled ones (e.g. menu.ts line 153). Maybe this still makes sense, but it would not be the same as arriving with `tab` there. Especially for the menu where both navigations are possible. But there are other components I think.
> 
> I believe the menu is the only component allowing both arrow and tab navigation. In general, if there is arrow navigation, you cannot tab between them

Ok, this can be. But also with only arrow-navigation components, should disabled buttons be reached now? Or don't we have any such case?

**Comment by TomMenga** [comment]
> > > A topic that came to my mind was that we have several components where we implemented arrow key navigation. Normally (as I remember) we exclude the disabled ones (e.g. menu.ts line 153). Maybe this still makes sense, but it would not be the same as arriving with `tab` there. Especially for the menu where both navigations are possible. But there are other components I think.
> > 
> > 
> > I believe the menu is the only component allowing both arrow and tab navigation. In general, if there is arrow navigation, you cannot tab between them
> 
> Ok, this can be. But also with only arrow-navigation components, should disabled buttons be reached now? Or don't we have any such case?

I'm not sure about it. Because in lists and groups, like the stepper or tab-group, screen readers allow users to navigate between items (even when disabled). Maybe we could ask for advice from an a11y expert

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thank you!

**Review by kyubisation — APPROVED** [review]
LGTM 👍 
Nice work! 😃

**Pull request merged**
